// Code generated by protoc-gen-imgui. DO NOT EDIT.

package proto

import (
	_ "github.com/inkyblackness/imgui-go/v4"
)

var (
	tmpFloat32 float32
)

func (m *Tuning) Render() {
	m.Tuning_Bg.Render()
}
