package main

import (
	"fmt"
	"html/template"
	"log"

	gamepb "github.com/jdf/todd-again/game/proto"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func emitFloat32(g *protogen.GeneratedFile, f *protogen.Field) {
	opts := f.Desc.Options().(*descriptorpb.FieldOptions)
	minspec := proto.GetExtension(opts, gamepb.E_Min)

	code := `
tmpFloat32 = p.Get{{.f.GoName}}()

{{if pipeline}} 
min :=  
{{else}} 
T0 
{{end}}
imgui.SliderFloat("{{.f.GoName}}", &tmpFloat32, .5*Default_{{.f.GoIdent.GoName}}, 2*Default_{{.f.GoIdent.GoName}})
if p.{{.f.GoName}} == nil {
	var f float32
	p.{{.f.GoName}} = &f
}
*p.{{.f.GoName}} = tmpFloat32
`
	t := template.Must(template.New("code").Parse(code))
	if err := t.Execute(g, map[string]interface{}{"f": f}); err != nil {
		log.Fatalf("failed to execute template: %v", err)
	}
}

func emitFloat64(g *protogen.GeneratedFile, f *protogen.Field) {
	name := f.GoName
	code := fmt.Sprintf(`
tmpFloat64 = p.Get%s()
imgui.InputFloat("%s", &tmpFloat64)
if p.%s == nil {
	var f float64
	p.%s = &f
}
*p.%s = tmpFloat64
	`, name, name, name, name, name)
	g.P(code)
}
func emitInt32(g *protogen.GeneratedFile, f *protogen.Field) {
	name := f.GoName
	code := fmt.Sprintf(`
tmpInt32 = p.Get%s()
imgui.InputInt("%s", &tmpInt32)
if p.%s == nil {
	var i int32
	p.%s = &i
}
*p.%s = tmpInt32
	`, name, name, name, name, name)
	g.P(code)
}

func emitString(g *protogen.GeneratedFile, f *protogen.Field) {
	name := f.GoName
	code := fmt.Sprintf(`
tmpString = p.Get%s()
imgui.InputText("%s", &tmpString)
if p.%s == nil {
	var s string
	p.%s = &s
}
*p.%s = tmpString
	`, name, name, name, name, name)
	g.P(code)
}

func emitMessage(g *protogen.GeneratedFile, m *protogen.Message) {

}

func emitFieldRenderingExpression(g *protogen.GeneratedFile, f *protogen.Field) {
	switch f.Desc.Kind() {
	case protoreflect.FloatKind:
		emitFloat32(g, f)
	case protoreflect.DoubleKind:
		emitFloat64(g, f)
	case protoreflect.Int32Kind:
		emitInt32(g, f)
	case protoreflect.StringKind:
		emitString(g, f)
	case protoreflect.MessageKind:
		emitMessage(g, f.Message)
	}
}

func emitColor(g *protogen.GeneratedFile, m *protogen.Message) {

}

func emitMessageRenderer(g *protogen.GeneratedFile, m *protogen.Message) {
	g.P(fmt.Sprintf("func Render%s(p *%s) {", m.GoIdent.GoName, g.QualifiedGoIdent(m.GoIdent)))
	for _, f := range m.Fields {
		emitFieldRenderingExpression(g, f)
	}
	g.P("}")
}

type varTypes struct {
	hasFloat32 bool
	hasFloat64 bool
	hasInt32   bool
	hasString  bool
	hasColor   bool
}

func (v *varTypes) gather(m *protogen.Message) {
	for _, f := range m.Fields {
		switch f.Desc.Kind() {
		case protoreflect.FloatKind:
			v.hasFloat32 = true
		case protoreflect.DoubleKind:
			v.hasFloat64 = true
		case protoreflect.Int32Kind:
			v.hasInt32 = true
		case protoreflect.StringKind:
			v.hasString = true
		case protoreflect.MessageKind:
			if f.Desc.FullName() == "game.Color" {
				v.hasColor = true
			} else {
				v.gather(f.Message)
			}
		default:
			log.Fatalf("unsupported field type: %v", f.Desc.Kind())
		}
	}
}

func emitVars(g *protogen.GeneratedFile, file *protogen.File) {
	v := varTypes{}
	for _, m := range file.Messages {
		v.gather(m)
	}
	g.P("var (")
	if v.hasFloat32 {
		g.P("tmpFloat32 float32")
	}
	if v.hasFloat64 {
		g.P("tmpFloat64 float64")
	}
	if v.hasInt32 {
		g.P("tmpInt32 int32")
	}
	if v.hasString {
		g.P("tmpString string")
	}
	if v.hasColor {
		g.P("tmpColor [3]float32")
	}
	g.P(")")
}

// generateFile generates go source to render a UI for editing the source proto.
func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_dear_imgui.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-imgui. DO NOT EDIT.")
	g.P("package ", file.GoPackageName)

	g.P(`import "github.com/inkyblackness/imgui-go/v4"`)

	emitVars(g, file)

	for _, m := range file.Messages {
		emitMessageRenderer(g, m)
	}
	g.Content()
}
