package main

import (
	"fmt"
	"log"

	"github.com/inkyblackness/imgui-go/v4"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func emitFloat32(g *protogen.GeneratedFile, f *protogen.Field) {
	g.P(fmt.Sprintf("tmpFloat32 = ", f.Name))
	imgui.SliderFloat("", &tmpFloat32, 0, 1)
	g.P(f.Name, " = tmpFloat32")
}

func emitFieldRenderingExpression(g *protogen.GeneratedFile, f *protogen.Field) {
	switch f.Desc.Kind() {
	case protoreflect.FloatKind:
		emitFloat32(g, f)
	case protoreflect.DoubleKind:
		emitFloat64(g, f)
	case protoreflect.Int32Kind:
		emitInt32(g, f)
	case protoreflect.StringKind:
		emitString(g, f)
	case protoreflect.MessageKind:
		emitMessage(g, f.Message)
	}
}

func emitColor(g *protogen.GeneratedFile, m *protogen.Message) {

}

func emitMessageRenderer(g *protogen.GeneratedFile, m *protogen.Message) {
	g.P(fmt.Sprintf("func Render%s() {", m.GoIdent.GoName))
	for _, f := range m.Fields {
		emitFieldRenderingExpression(g, f)
	}
	g.P("}")
}

type varTypes struct {
	hasFloat32 bool
	hasFloat64 bool
	hasInt32   bool
	hasString  bool
	hasColor   bool
}

func (v *varTypes) gather(m *protogen.Message) {
	for _, f := range m.Fields {
		switch f.Desc.Kind() {
		case protoreflect.FloatKind:
			v.hasFloat32 = true
		case protoreflect.DoubleKind:
			v.hasFloat64 = true
		case protoreflect.Int32Kind:
			v.hasInt32 = true
		case protoreflect.StringKind:
			v.hasString = true
		case protoreflect.MessageKind:
			if f.Desc.FullName() == "game.Color" {
				v.hasColor = true
			} else {
				v.gather(f.Message)
			}
		default:
			log.Fatalf("unsupported field type: %v", f.Desc.Kind())
		}
	}
}

// generateFile generates go source to render a UI for editing the source proto.
func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_dear_imgui.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-imgui. DO NOT EDIT.")
	g.Import("github.com/inkyblackness/imgui-go/v4")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	v := varTypes{}
	for _, m := range file.Messages {
		v.gather(m)
	}
	g.P("var (")
	if v.hasFloat32 {
		g.P("tmpFloat32 float32")
	}
	if v.hasFloat64 {
		g.P("tmpFloat64 float64")
	}
	if v.hasInt32 {
		g.P("tmpInt32 int32")
	}
	if v.hasString {
		g.P("tmpString string")
	}
	if v.hasColor {
		g.P("tmpColor [3]float32")
	}
	g.P(")")
	g.P()

	for _, m := range file.Messages {
		emitMessageRenderer(g, m)
	}
	g.Content()
}
